---
name: "luarocks upload"
on:
  push:
    tags:
      - '*'
  release: 
    types:
      - created # Triggered by release-please
  pull_request: # Tests a local luarocks install without publishing on PRs
  workflow_dispatch: # Allow manual trigger
jobs:
  luarocks-upload:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required to count the commits
      - name: Get Version
        # Tags created by GitHub releases don't trigger push: tags workflows
        # So we have to determine the tag manually.
        run: echo "LUAROCKS_VERSION=$(git describe --abbrev=0 --tags)" >> $GITHUB_ENV
      - name: LuaRocks Upload
        uses: nvim-neorocks/luarocks-tag-release@v5
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          version: ${{ env.LUAROCKS_VERSION }}
          detailed_description: |
            Vim's diff mode is pretty good, but there is no convenient way to quickly bring up all modified files in a diffsplit.
            This plugin aims to provide a simple, unified, single tabpage interface that lets you easily review all changed files for any git rev.
          license: "GPL-3.0"
          dependencies: |
            nvim-web-devicons
