---
name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
        with:
          release-type: simple
          package-name: diffview.nvim
